import type { NoteLocale } from "@/lib/note/prefs";

const ID = {
  journal: "Jurnal",
  baru: "Baru",
  impor: "Impor",
  setelan: "Setelan",
  profil: "Profil",
  support: "Bantuan",
  kelas: "Kelas",
  disclaimer: "Disclaimer",
  keluar: "Keluar",
  masuk: "Masuk",
  language: "Bahasa",
  currency: "Mata uang",
  theme: "Tema",
  themeDark: "Gelap",
  themeLight: "Terang",
  themeSystem: "Sistem",
  jenis: "Jenis",
  semua: "Semua",
  trade: "Trade",
  invest: "Invest",
  refleksi: "Refleksi",
  modeEntry: "Mode entry",
  modeCepat: "Cepat",
  modeReview: "Review",
  linkKelas: "Tautan kelas (opsional)",
  lihatKelas: "Lihat di katalog",
  catatanRefleksi: "Refleksi belajar",
  notesCapturePlaceholder: "Tulis apa saja tentang pasar… (Ctrl+Enter simpan)",
  notesCaptureHint: "Tanpa format wajib. Tag otomatis di belakang layar.",
  notesCaptureSave: "Simpan belief",
  notesSaveError: "Gagal menyimpan.",
  notesEmpty: "Belum ada belief note. Tulis di kotak atas - boleh salah, boleh random.",
  notesStreamTitle: "Belief stream",
  notesAdvancedLink: "Form lengkap (opsional)",
  notesLinkOptional: "Link opsional",
  notesLinkJournal: "Journal",
  notesLinkJournalNone: "- Journal -",
  notesLinkPlaybook: "Playbook setup",
  notesLinkPlaybookNone: "- Setup -",
  notesLinkPlaybookOpen: "Playbook →",
  notesMirrorTitle: "Mirror sinyal (bukan nilai)",
  notesMirrorHint:
    "Catatan = cheap talk. Commit ke Playbook hanya kalau kamu tekan adopt (costly signal).",
  notesMirrorAction: "Lihat arah →",
  notesAdoptPlaybook: "Adopt ke setup aktif",
  notesAdoptedPlaybook: "Sudah di setup",
  notesDismissPromotion: "Abaikan",
  playbookNotesBridgeTitle: "Jembatan Notes",
  playbookNotesBridgeHint:
    "Pola berulang dari Notes menunggu commit eksplisit. Gate tidak berubah sampai kamu adopt.",
  playbookNotesBridgeOpen: "Buka Notes →",
  aturanDilanggar: "Aturan yang dilanggar",
  pelajaran: "Pelajaran hari ini",
  kembaliKelas: "Kembali ke kelas",
  ringkasan: "Ringkasan",
  entry: "Entry",
  net: "Net",
  win: "Win",
  updated: "Diperbarui",
  waktu: "Waktu",
  bantuan: "Bantuan",
  privasi: "Privasi",
  privacyBody: "Jurnal privat. Win rate tidak dibagikan. Tanpa password broker.",
  jakarta: "Asia/Jakarta",
  contoh: "Data contoh · tidak tersimpan.",
  trackDemo: "Angka portfolio ini contoh. Bukan holdings kamu.",
  menu: "Menu",
  skipToContent: "Loncat ke isi",
  hideSidebar: "Sembunyikan sidebar",
  showSidebar: "Tampilkan sidebar",
  navTrade: "Trade",
  navInvest: "Invest",
  accountEmail: "Email yang dipakai",
  numberFormat: "Format angka",
  heroNet: "Hero net",
  defaultKind: "Jenis entry default",
  calendarNumbers: "Angka di sel kalender",
  weekStart: "Awal minggu",
  decimals: "Desimal",
  lossStyle: "Gaya rugi",
  colorMode: "Warna angka",
  density: "Kepadatan",
  emotionPrompt: "Prompt emosi",
  advanced: "Lanjutan",
  reset: "Kembalikan default",
  compact: "Compact",
  full: "Penuh",
  allFilter: "Semua filter",
  visibleMonth: "Bulan terlihat",
  show: "Tampilkan",
  dateOnly: "Tanggal saja",
  sunday: "Minggu",
  monday: "Senin",
  minus: "Tanda −",
  paren: "( )",
  hue: "Hijau / merah",
  pattern: "Pola",
  comfortable: "Longgar",
  dense: "Rapat",
  optional: "Opsional",
  afterLoss: "Tawarkan setelah rugi",
  currencyHint: "Mata uang laporan. Agregat multi-mata uang dikonversi dengan kurs USD/IDR di bawah.",
  usdIdrRate: "Kurs USD/IDR",
  usdIdrRateHint: "Otomatis dari pasar (USDIDR). Tidak perlu diisi manual.",
  languageHint: "Menyimpan preferensi Note. Situs Bursa tetap Bahasa Indonesia.",
  themeHint: "Hanya permukaan Note.",
  noStreak: "Trading tidak harus setiap hari. Tidak ada hukuman jika kamu skip.",
  locked: "Zona waktu Asia/Jakarta. Jurnal privat. Win rate tidak dibagikan.",
  tulis: "Tulis",
  lihat: "Lihat",
  filter: "Filter",
  akun: "Akun",
  polaMinggu: "Pola minggu",
  tutup: "Tutup",
  lepas: "Lepas",
  hariItu: "Hari itu",
  belumAda: "Belum ada entry.",
  belumAdaHari: "Tidak ada entry pada tanggal ini.",
  tulisSatu: "Tulis satu",
  kurva: "Kurva",
  expectansi: "Expectansi",
  diperbarui: "Diperbarui",
  scopeFilter: "Seluruh filter, bukan hari yang diklik",
  simpan: "Simpan",
  menyimpan: "Menyimpan…",
  batal: "Batal",
  tampilan: "Tampilan",
  angka: "Angka",
  bursaAccount: "Akun Bursa",
  belumMasuk: "Belum masuk",
  privacyFoot: "Jurnal privat. Win rate tidak dibagikan.",
  privacyMode: "Mode privasi",
  privacyModeHint: "Samarkan semua nominal (Rp•••) saat berbagi layar. Chart tidak berubah.",
  terbaru: "Terbaru",
  log: "Log",
  colDate: "Tanggal",
  colSymbol: "Simbol",
  colSide: "Sisi",
  colMode: "Mode",
  ruleShort: "Aturan",
  lessonShort: "Pelajaran",
  classShort: "kelas",
  loading: "Memuat…",
  loadingJournal: "Memuat jurnal…",
  journalRows: "baris",
  saveFailed: "Gagal menyimpan.",
  numberFormatCompactHint:
    "Compact memakai rb (ribu), jt (juta), mld (miliar), trl (triliun) agar sel kalender tidak pecah.",
  heroNetHint: "Hari yang diklik tidak pernah mengubah angka ini.",
  colorModePatternHint: "Pola memakai garis bawah pada rugi, bukan merah/hijau saja.",
  underDev: "Masih dalam pengembangan",
  aiTitle: "Asisten Note",
  aiPlaceholder: "Tanya singkat…",
  aiAskAnything: "Tanya apa saja tentang jurnalmu…",
  aiSend: "Kirim",
  aiDisclaimer: "Edukasi & jurnal saja. Bukan sinyal, bukan saran ukuran posisi.",
  aiWelcomeBack: "Senang kamu kembali. Ada yang bisa kubantu?",
  aiWelcomeSub:
    "Aku baca stat jurnalmu (bukan ekuitas broker). Pilih prompt di bawah atau ketik sendiri.",
  aiShortcuts: "Pintasan",
  aiModeLabel: "Note · Jurnal",
  aiNewChat: "Mulai ulang",
  aiQuickPrompts: "Prompt cepat",
  aiStatNet: "Net",
  aiStatStreak: "Streak log",
  aiStatWin: "Win",
  aiPromptSummarize: "Ringkas kondisiku",
  aiPromptTilt: "Cek tilt",
  aiPromptWeek: "Review minggu ini",
  aiPromptEcon: "Kalender ekonomi",
  aiPromptLog: "Tips log cepat",
  aiPromptMore: "Lainnya",
  econCalendar: "Kalender ekonomi",
  econColDate: "Tanggal",
  econColTime: "Jam",
  econColCurrency: "Mata uang",
  econColImpact: "Dampak",
  econColEvent: "Event",
  econColActual: "Aktual",
  econColForecast: "Prakiraan",
  econColPrevious: "Sebelumnya",
  econColDetail: "Detail",
  econEmpty: "Tidak ada event untuk filter ini.",
  econDisclaimer:
    "Feed pihak ketiga (Forex Factory / mirror JSON). Bukan afiliasi FF. Cek jam resmi sebelum trade.",
  econNextEvent: "Event terdekat",
  econVolatilityHint: "Volatility weight: CPI/NFP/FOMC masuk fase detik lebih awal (20 menit).",
  econFilterImpact: "Dampak diharapkan",
  econFilterTypes: "Jenis event",
  econFilterCurrencies: "Mata uang",
  econAll: "semua",
  econNone: "tidak ada",
  econRangeTitle: "Rentang tanggal",
  econRangeFrom: "Dari",
  econRangeTo: "Sampai",
  econRangeToday: "Hari ini",
  econRangeThisWeek: "Minggu ini",
  econRangeNextWeek: "Minggu depan",
  econRangeThisMonth: "Bulan ini",
  econRangeNextMonth: "Bulan depan",
  econRangeResetToday: "Reset ke hari ini",
  econRangePrev: "Hari sebelumnya",
  econRangeNext: "Hari berikutnya",
  econApplyFilter: "Terapkan filter",
  econRemoveFilter: "Hapus filter",
  newsTitle: "News",
  newsAssetSensitivity: "Sensitivitas aset",
  newsChartsTitle: "Chart (TradingView)",
  newsChartsHint:
    "Satu keputusan filter = event + chart. Pair hanya dari mata uang yang sudah diterapkan di bawah.",
  newsChartsBroadFilter: "Filter → pilih 1–4 mata uang → Terapkan agar chart ikut.",
  newsChartsFilterLock: "Mata uang aktif (filter):",
  newsChartsCurrencyLocked: "Dikunci oleh filter kalender",
  newsChartsOnApply: "Setelah Terapkan, chart mengikuti:",
  newsChartsSync: "Sinkron filter:",
  newsChartsLayout: "Layout chart",
  newsChartsLayout1: "Satu chart",
  newsChartsLayout2col: "Dua chart berdampingan",
  newsChartsLayout2row: "Dua chart bertumpuk",
  newsChartsLayoutGrid: "Empat chart",
  newsChartsPane: "Panel",
  newsChartsCurrency: "Mata uang",
  newsChartsPair: "Pair",
  logTrade: "Log trade",
  importFile: "File CSV",
  importFileHint: "Header: symbol, side, qty, entry, exit, pnl, date. Tanpa password broker.",
  playbookSetupHint:
    "Aturan kamu. Menu Contoh hanya starter opsional (ICT, breakout, dan sejenisnya). Tidak dipakai sampai kamu pilih.",
  tapPrefs: "Ketuk untuk preferensi",
  trackCreate: "Buat portfolio",
  trackAddTx: "Tambah transaksi",
  trackAllPortfolios: "Semua portfolio",
  newsChartsDisclaimer: "Widget TradingView · bukan sinyal Bursanalar. Data & delay sesuai TradingView.",
  newsMonthHint:
    "Rentang bulan ini dari cache scrape lokal + mirror FF (mingguan). Perketat filter di panel bawah.",
  econImpactLabels: {
    high: "High",
    medium: "Medium",
    low: "Low",
    holiday: "Non-economic",
  },
  econTypeLabels: {
    growth: "Growth",
    inflation: "Inflation",
    employment: "Employment",
    central_bank: "Central bank",
    bonds: "Bonds",
    housing: "Housing",
    consumer_surveys: "Consumer surveys",
    business_surveys: "Business surveys",
    speeches: "Speeches",
    misc: "Misc",
  },
};

const EN: typeof ID = {
  journal: "Journal",
  baru: "New",
  impor: "Import",
  setelan: "Settings",
  profil: "Profile",
  support: "Help",
  kelas: "Classes",
  disclaimer: "Disclaimer",
  keluar: "Log out",
  masuk: "Sign in",
  language: "Language",
  currency: "Currency",
  theme: "Theme",
  themeDark: "Dark",
  themeLight: "Light",
  themeSystem: "System",
  jenis: "Kind",
  semua: "All",
  trade: "Trade",
  invest: "Invest",
  refleksi: "Reflection",
  modeEntry: "Entry mode",
  modeCepat: "Quick",
  modeReview: "Review",
  linkKelas: "Class link (optional)",
  lihatKelas: "View in catalog",
  catatanRefleksi: "Learning reflection",
  notesCapturePlaceholder: "Write anything about the market… (Ctrl+Enter to save)",
  notesCaptureHint: "No required format. Tags run in the background.",
  notesCaptureSave: "Save belief",
  notesSaveError: "Could not save.",
  notesEmpty: "No belief notes yet. Use the box above - wrong or random is fine.",
  notesStreamTitle: "Belief stream",
  notesAdvancedLink: "Full form (optional)",
  notesLinkOptional: "Optional link",
  notesLinkJournal: "Journal",
  notesLinkJournalNone: "- Journal -",
  notesLinkPlaybook: "Playbook setup",
  notesLinkPlaybookNone: "- Setup -",
  notesLinkPlaybookOpen: "Open Playbook →",
  notesMirrorTitle: "Signal mirror (not judgment)",
  notesMirrorHint:
    "Notes are cheap talk. Playbook changes only when you press adopt (costly signal).",
  notesMirrorAction: "Follow up →",
  notesAdoptPlaybook: "Adopt to active setup",
  notesAdoptedPlaybook: "Added to setup",
  notesDismissPromotion: "Dismiss",
  playbookNotesBridgeTitle: "Notes bridge",
  playbookNotesBridgeHint:
    "Repeating note patterns wait for explicit commit. Gate does not change until you adopt.",
  playbookNotesBridgeOpen: "Open Notes →",
  aturanDilanggar: "Rule broken",
  pelajaran: "Lesson learned",
  kembaliKelas: "Back to classes",
  ringkasan: "Summary",
  entry: "Entries",
  net: "Net",
  win: "Win",
  updated: "Updated",
  waktu: "Time",
  bantuan: "Help",
  privasi: "Privacy",
  privacyBody: "Private journal. Win rate is not shared. No broker passwords.",
  jakarta: "Asia/Jakarta",
  contoh: "Sample data · not saved.",
  trackDemo: "These portfolio numbers are sample data. Not your holdings.",
  menu: "Menu",
  skipToContent: "Skip to content",
  hideSidebar: "Hide sidebar",
  showSidebar: "Show sidebar",
  navTrade: "Trade",
  navInvest: "Invest",
  accountEmail: "Signed in as",
  numberFormat: "Number format",
  heroNet: "Hero net",
  defaultKind: "Default entry kind",
  calendarNumbers: "Numbers in calendar cells",
  weekStart: "Week starts",
  decimals: "Decimals",
  lossStyle: "Loss style",
  colorMode: "Color",
  density: "Density",
  emotionPrompt: "Emotion prompt",
  advanced: "Advanced",
  reset: "Reset defaults",
  compact: "Compact",
  full: "Full",
  allFilter: "All in filter",
  visibleMonth: "Visible month",
  show: "Show",
  dateOnly: "Date only",
  sunday: "Sunday",
  monday: "Monday",
  minus: "Minus sign",
  paren: "( )",
  hue: "Green / red",
  pattern: "Pattern",
  comfortable: "Comfortable",
  dense: "Compact",
  optional: "Optional",
  afterLoss: "Offer after a loss",
  currencyHint: "Reporting currency. Multi-currency totals convert using USD/IDR below.",
  usdIdrRate: "USD/IDR rate",
  usdIdrRateHint: "Auto-filled from market (USDIDR). No manual input needed.",
  languageHint: "Note UI preference. Bursa site stays Bahasa Indonesia.",
  themeHint: "Note surface only.",
  noStreak: "You do not need to trade every day. Skipping a day is fine.",
  locked: "Timezone Asia/Jakarta. Private journal. Win rate is not shared.",
  tulis: "Write",
  lihat: "View",
  filter: "Filter",
  akun: "Account",
  polaMinggu: "Week pattern",
  tutup: "Close",
  lepas: "Clear",
  hariItu: "That day",
  belumAda: "No entries yet.",
  belumAdaHari: "No entries on this date.",
  tulisSatu: "Log one",
  kurva: "Curve",
  expectansi: "Expectancy",
  diperbarui: "Updated",
  scopeFilter: "Whole filter, not the clicked day",
  simpan: "Save",
  menyimpan: "Saving…",
  batal: "Cancel",
  tampilan: "Display",
  angka: "Numbers",
  bursaAccount: "Bursa account",
  belumMasuk: "Not signed in",
  privacyFoot: "Private journal. Win rate is not shared.",
  privacyMode: "Privacy mode",
  privacyModeHint: "Mask every monetary value (•••) when sharing screen. Charts keep their shape.",
  terbaru: "Latest",
  log: "Log",
  colDate: "Date",
  colSymbol: "Symbol",
  colSide: "Side",
  colMode: "Mode",
  ruleShort: "Rule",
  lessonShort: "Lesson",
  classShort: "class",
  loading: "Loading…",
  loadingJournal: "Loading journal…",
  journalRows: "rows",
  saveFailed: "Could not save.",
  numberFormatCompactHint:
    "Compact uses k (thousand), m (million), b (billion), t (trillion) so calendar cells stay readable.",
  heroNetHint: "Clicking a day never changes this total.",
  colorModePatternHint: "Pattern mode underlines losses instead of relying on green/red only.",
  underDev: "Still under development",
  aiTitle: "Note assistant",
  aiPlaceholder: "Ask briefly…",
  aiAskAnything: "Ask me anything about your journal…",
  aiSend: "Send",
  aiDisclaimer: "Education & journaling only. Not signals or sizing advice.",
  aiWelcomeBack: "Welcome back. How can I help?",
  aiWelcomeSub:
    "I read your journal stats (not broker equity). Pick a prompt below or type your own.",
  aiShortcuts: "Shortcuts",
  aiModeLabel: "Note · Journal",
  aiNewChat: "Start over",
  aiQuickPrompts: "Quick prompts",
  aiStatNet: "Net",
  aiStatStreak: "Log streak",
  aiStatWin: "Win",
  aiPromptSummarize: "Summarize my state",
  aiPromptTilt: "Tilt check",
  aiPromptWeek: "This week",
  aiPromptEcon: "Economic calendar",
  aiPromptLog: "Quick log tips",
  aiPromptMore: "More",
  econCalendar: "Economic calendar",
  econColDate: "Date",
  econColTime: "Time",
  econColCurrency: "Currency",
  econColImpact: "Impact",
  econColEvent: "Event",
  econColActual: "Actual",
  econColForecast: "Forecast",
  econColPrevious: "Previous",
  econColDetail: "Detail",
  econEmpty: "No events for this filter.",
  econDisclaimer:
    "Third-party feed (Forex Factory / JSON mirror). Not affiliated. Verify official times before trading.",
  econNextEvent: "Next event",
  econVolatilityHint: "Volatility weight: CPI/NFP/FOMC enter the seconds phase earlier (20 min).",
  econFilterImpact: "Expected impact",
  econFilterTypes: "Event types",
  econFilterCurrencies: "Currencies",
  econAll: "all",
  econNone: "none",
  econRangeTitle: "Date range",
  econRangeFrom: "From",
  econRangeTo: "To",
  econRangeToday: "Today",
  econRangeThisWeek: "This week",
  econRangeNextWeek: "Next week",
  econRangeThisMonth: "This month",
  econRangeNextMonth: "Next month",
  econRangeResetToday: "Reset to today",
  econRangePrev: "Previous day",
  econRangeNext: "Next day",
  econApplyFilter: "Apply filter",
  econRemoveFilter: "Remove filter",
  newsTitle: "News",
  newsAssetSensitivity: "Asset sensitivity",
  newsChartsTitle: "Charts (TradingView)",
  newsChartsHint:
    "One filter commit drives events + charts. Pairs only from currencies already applied below.",
  newsChartsBroadFilter: "Filter → pick 1–4 currencies → Apply to sync charts.",
  newsChartsFilterLock: "Active currencies (filter):",
  newsChartsCurrencyLocked: "Locked by calendar filter",
  newsChartsOnApply: "After Apply, charts follow:",
  newsChartsSync: "Filter sync:",
  newsChartsLayout: "Chart layout",
  newsChartsLayout1: "One chart",
  newsChartsLayout2col: "Two charts side by side",
  newsChartsLayout2row: "Two charts stacked",
  newsChartsLayoutGrid: "Four charts",
  newsChartsPane: "Pane",
  newsChartsCurrency: "Currency",
  newsChartsPair: "Pair",
  logTrade: "Log trade",
  importFile: "CSV file",
  importFileHint: "Header: symbol, side, qty, entry, exit, pnl, date. No broker password.",
  playbookSetupHint:
    "Your rules. The Example menu is an optional starter (ICT, breakout, and so on). Nothing applies until you pick one.",
  tapPrefs: "Tap for preferences",
  trackCreate: "Create portfolio",
  trackAddTx: "Add transaction",
  trackAllPortfolios: "All portfolios",
  newsChartsDisclaimer: "TradingView widget · not Bursanalar signals. Data & delay per TradingView.",
  newsMonthHint:
    "This month from local scrape cache + FF mirror (weekly). Tighten filters in the panel below.",
  econImpactLabels: {
    high: "High",
    medium: "Medium",
    low: "Low",
    holiday: "Non-economic",
  },
  econTypeLabels: {
    growth: "Growth",
    inflation: "Inflation",
    employment: "Employment",
    central_bank: "Central bank",
    bonds: "Bonds",
    housing: "Housing",
    consumer_surveys: "Consumer surveys",
    business_surveys: "Business surveys",
    speeches: "Speeches",
    misc: "Misc",
  },
};

export function noteCopy(locale: NoteLocale) {
  return locale === "en" ? EN : ID;
}

export function journalKindLabel(kind: string, locale: NoteLocale): string {
  const c = noteCopy(locale);
  if (kind === "REFLEKSI") return c.refleksi;
  if (kind === "TRADE") return c.trade;
  if (kind === "INVEST") return c.invest;
  return kind;
}

export function journalModeLabel(mode: string, locale: NoteLocale): string {
  const c = noteCopy(locale);
  if (mode === "cepat") return c.modeCepat;
  if (mode === "review") return c.modeReview;
  return mode;
}
