import type { NoteLocale } from "@/lib/note/prefs";

const ID = {
  journal: "Jurnal",
  baru: "Baru",
  impor: "Impor",
  setelan: "Setelan",
  profil: "Profil",
  support: "Bantuan",
  kelas: "Kelas",
  disclaimer: "Disclaimer",
  keluar: "Keluar",
  masuk: "Masuk",
  language: "Bahasa",
  currency: "Mata uang",
  theme: "Tema",
  themeDark: "Gelap",
  themeLight: "Terang",
  themeSystem: "Sistem",
  jenis: "Jenis",
  semua: "Semua",
  trade: "Trade",
  invest: "Invest",
  ringkasan: "Ringkasan",
  entry: "Entry",
  net: "Net",
  win: "Win",
  updated: "Diperbarui",
  waktu: "Waktu",
  bantuan: "Bantuan",
  privasi: "Privasi",
  privacyBody: "Jurnal privat. Win rate tidak dibagikan. Tanpa password broker.",
  jakarta: "Asia/Jakarta",
  contoh: "Data contoh · tidak tersimpan.",
  menu: "Menu",
  accountEmail: "Email yang dipakai",
  numberFormat: "Format angka",
  heroNet: "Hero net",
  defaultKind: "Jenis entry default",
  calendarNumbers: "Angka di sel kalender",
  weekStart: "Awal minggu",
  decimals: "Desimal",
  lossStyle: "Gaya rugi",
  colorMode: "Warna angka",
  density: "Kepadatan",
  emotionPrompt: "Prompt emosi",
  advanced: "Lanjutan",
  reset: "Kembalikan default",
  compact: "Compact",
  full: "Penuh",
  allFilter: "Semua filter",
  visibleMonth: "Bulan terlihat",
  show: "Tampilkan",
  dateOnly: "Tanggal saja",
  sunday: "Minggu",
  monday: "Senin",
  minus: "Tanda −",
  paren: "( )",
  hue: "Hijau / merah",
  pattern: "Pola",
  comfortable: "Longgar",
  dense: "Rapat",
  optional: "Opsional",
  afterLoss: "Tawarkan setelah rugi",
  currencyHint: "Label tampilan pada PnL. Bukan kurs, angka tidak dikonversi.",
  languageHint: "Menyimpan preferensi Note. Situs Bursa tetap Bahasa Indonesia.",
  themeHint: "Hanya permukaan Note.",
  noStreak: "Trading tidak harus setiap hari. Tidak ada hukuman jika kamu skip.",
  locked: "Zona waktu Asia/Jakarta. Jurnal privat. Win rate tidak dibagikan.",
  tulis: "Tulis",
  lihat: "Lihat",
  filter: "Filter",
  akun: "Akun",
  polaMinggu: "Pola minggu",
  tutup: "Tutup",
  lepas: "Lepas",
  hariItu: "Hari itu",
  belumAda: "Belum ada entry.",
  belumAdaHari: "Tidak ada entry pada tanggal ini.",
  tulisSatu: "Tulis satu",
  kurva: "Kurva",
  expectansi: "Expectansi",
  diperbarui: "Diperbarui",
  scopeFilter: "Seluruh filter, bukan hari yang diklik",
  simpan: "Simpan",
  menyimpan: "Menyimpan…",
  batal: "Batal",
  tampilan: "Tampilan",
  angka: "Angka",
  bursaAccount: "Akun Bursa",
  belumMasuk: "Belum masuk",
  privacyFoot: "Jurnal privat. Win rate tidak dibagikan.",
  terbaru: "Terbaru",
  log: "Log",
};

const EN: typeof ID = {
  journal: "Journal",
  baru: "New",
  impor: "Import",
  setelan: "Settings",
  profil: "Profile",
  support: "Help",
  kelas: "Classes",
  disclaimer: "Disclaimer",
  keluar: "Log out",
  masuk: "Sign in",
  language: "Language",
  currency: "Currency",
  theme: "Theme",
  themeDark: "Dark",
  themeLight: "Light",
  themeSystem: "System",
  jenis: "Kind",
  semua: "All",
  trade: "Trade",
  invest: "Invest",
  ringkasan: "Summary",
  entry: "Entries",
  net: "Net",
  win: "Win",
  updated: "Updated",
  waktu: "Time",
  bantuan: "Help",
  privasi: "Privacy",
  privacyBody: "Private journal. Win rate is not shared. No broker passwords.",
  jakarta: "Asia/Jakarta",
  contoh: "Sample data · not saved.",
  menu: "Menu",
  accountEmail: "Signed in as",
  numberFormat: "Number format",
  heroNet: "Hero net",
  defaultKind: "Default entry kind",
  calendarNumbers: "Numbers in calendar cells",
  weekStart: "Week starts",
  decimals: "Decimals",
  lossStyle: "Loss style",
  colorMode: "Color",
  density: "Density",
  emotionPrompt: "Emotion prompt",
  advanced: "Advanced",
  reset: "Reset defaults",
  compact: "Compact",
  full: "Full",
  allFilter: "All in filter",
  visibleMonth: "Visible month",
  show: "Show",
  dateOnly: "Date only",
  sunday: "Sunday",
  monday: "Monday",
  minus: "Minus sign",
  paren: "( )",
  hue: "Green / red",
  pattern: "Pattern",
  comfortable: "Comfortable",
  dense: "Compact",
  optional: "Optional",
  afterLoss: "Offer after a loss",
  currencyHint: "Display label on PnL. Not an FX rate; figures are not converted.",
  languageHint: "Note UI preference. Bursa site stays Bahasa Indonesia.",
  themeHint: "Note surface only.",
  noStreak: "You do not need to trade every day. Skipping a day is fine.",
  locked: "Timezone Asia/Jakarta. Private journal. Win rate is not shared.",
  tulis: "Write",
  lihat: "View",
  filter: "Filter",
  akun: "Account",
  polaMinggu: "Week pattern",
  tutup: "Close",
  lepas: "Clear",
  hariItu: "That day",
  belumAda: "No entries yet.",
  belumAdaHari: "No entries on this date.",
  tulisSatu: "Log one",
  kurva: "Curve",
  expectansi: "Expectancy",
  diperbarui: "Updated",
  scopeFilter: "Whole filter, not the clicked day",
  simpan: "Save",
  menyimpan: "Saving…",
  batal: "Cancel",
  tampilan: "Display",
  angka: "Numbers",
  bursaAccount: "Bursa account",
  belumMasuk: "Not signed in",
  privacyFoot: "Private journal. Win rate is not shared.",
  terbaru: "Latest",
  log: "Log",
};

export function noteCopy(locale: NoteLocale) {
  return locale === "en" ? EN : ID;
}
