import type { JournalEntry } from "@/lib/note/types";

/** Local-only sample so the journal chrome can be reviewed without a session. */
export const NOTE_DEMO_USER = "local-demo";

function daysAgo(n: number, hour = 10): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  d.setHours(hour, 15, 0, 0);
  return d.toISOString();
}

export const NOTE_DEMO_ENTRIES: JournalEntry[] = [
  {
    id: "demo-1",
    apexUserId: NOTE_DEMO_USER,
    kind: "TRADE",
    mode: "cepat",
    symbol: "EURUSD",
    side: "BUY",
    qty: 0.1,
    entryPrice: 1.084,
    exitPrice: 1.087,
    fees: 2,
    pnl: 28,
    result: "win",
    emotion: "tenang",
    note: "Break London, stop dipegang.",
    ruleBroken: null,
    lesson: null,
    clinicModuleId: null,
    protocol: null,
    accountLabel: "Demo",
    openedAt: daysAgo(1, 9),
    createdAt: daysAgo(1, 9),
  },
  {
    id: "demo-2",
    apexUserId: NOTE_DEMO_USER,
    kind: "TRADE",
    mode: "review",
    symbol: "XAUUSD",
    side: "SELL",
    qty: 0.05,
    entryPrice: 2480,
    exitPrice: 2492,
    fees: 4,
    pnl: -62,
    result: "loss",
    emotion: "marah",
    note: "Revenge setelah loss pagi.",
    ruleBroken: "Tidak ada setup, hanya chase.",
    lesson: "Cap 2 loss lalu berhenti sesi.",
    clinicModuleId: null,
    protocol: null,
    accountLabel: "Demo",
    openedAt: daysAgo(1, 14),
    createdAt: daysAgo(1, 14),
  },
  {
    id: "demo-3",
    apexUserId: NOTE_DEMO_USER,
    kind: "INVEST",
    mode: "klinik",
    symbol: "BBCA",
    side: "HOLD",
    qty: 100,
    entryPrice: 9250,
    exitPrice: null,
    fees: 0,
    pnl: 0,
    result: "open",
    emotion: "cemas",
    note: "Thesis 3 kalimat masih utuh, cek terlalu sering.",
    ruleBroken: "Buka porto 8 kali hari ini.",
    lesson: "Satu jendela cek per minggu.",
    clinicModuleId: "sering-cek",
    protocol: "Jadwalkan 1 jendela cek per minggu. Matikan push harga.",
    accountLabel: "Saham",
    openedAt: daysAgo(4, 11),
    createdAt: daysAgo(4, 11),
  },
  {
    id: "demo-4",
    apexUserId: NOTE_DEMO_USER,
    kind: "TRADE",
    mode: "cepat",
    symbol: "BTCUSDT",
    side: "BUY",
    qty: 0.01,
    entryPrice: 108400,
    exitPrice: 109100,
    fees: 8,
    pnl: 54,
    result: "win",
    emotion: "FOMO",
    note: "Masuk karena thread, bukan checklist.",
    ruleBroken: null,
    lesson: null,
    clinicModuleId: null,
    protocol: null,
    accountLabel: "Demo",
    openedAt: daysAgo(6, 21),
    createdAt: daysAgo(6, 21),
  },
  {
    id: "demo-5",
    apexUserId: NOTE_DEMO_USER,
    kind: "TRADE",
    mode: "cepat",
    symbol: "NAS100",
    side: "BUY",
    qty: 1,
    entryPrice: 19820,
    exitPrice: 19820,
    fees: 3,
    pnl: -3,
    result: "be",
    emotion: "lega",
    note: "Stop ke BE, tidak dipaksa jadi win.",
    ruleBroken: null,
    lesson: null,
    clinicModuleId: null,
    protocol: null,
    accountLabel: "Demo",
    openedAt: daysAgo(8, 16),
    createdAt: daysAgo(8, 16),
  },
];
