/**
 * Single source of truth for the developer docs sidebar/TOC + client-side search.
 * Keep `id` in sync with the `id` prop on each <DocSection> in
 * src/app/developer/docs/page.tsx — the nav links to `#${id}`.
 *
 * `keywords` are extra search terms (route paths, code identifiers, synonyms)
 * that don't appear in the visible label, so the search box can match on
 * content, not just headings.
 */

export interface DocNavSection {
  id: string;
  number?: string;
  label: string;
  keywords?: string[];
}

export const DOC_NAV_SECTIONS: DocNavSection[] = [
  {
    id: "arsitektur",
    number: "1",
    label: "Arsitektur overview",
    keywords: [
      "stack",
      "next.js",
      "app router",
      "react",
      "typescript",
      "tailwind",
      "prisma",
      "postgresql",
      "neon",
      "zod",
      "motion",
      "folder structure",
      "src/app",
      "src/components",
      "src/lib",
      "schema.prisma",
    ],
  },
  {
    id: "roles",
    number: "2",
    label: "Empat user roles",
    keywords: [
      "learner",
      "mentor",
      "admin",
      "developer",
      "UserRole",
      "roles.ts",
      "canAccessAdminPanel",
      "canMutateAdmin",
      "canAccessMentorPanel",
      "canMutateMentor",
      "isQcViewer",
      "getRoleNavLinks",
      "guard",
      "permission",
    ],
  },
  {
    id: "auth",
    number: "3",
    label: "Auth (client + Prisma bridge)",
    keywords: [
      "login",
      "register",
      "daftar",
      "masuk",
      "localStorage",
      "bursa-session",
      "bursa-users",
      "bursa-auth-change",
      "AuthProvider",
      "RoleGuard",
      "AdminGuard",
      "ensure-user",
      "x-user-email",
      "requireAdmin",
      "resolveRequestUser",
      "session",
    ],
  },
  {
    id: "chat",
    number: "4",
    label: "Sistem chat",
    keywords: [
      "komunitas",
      "room",
      "branch",
      "cabang",
      "PUBLIC",
      "MENTOR_COMMUNITY",
      "MENTOR_INTERNAL",
      "ONE_WAY",
      "TWO_WAY",
      "visibility",
      "private",
      "unread",
      "mention",
      "reaction",
      "poll",
      "signal",
      "polling",
      "ChatRoom",
      "ChatBranch",
      "ChatRoomMember",
    ],
  },
  {
    id: "kursus",
    number: "5",
    label: "Kursus / kurikulum & usulan mentor",
    keywords: [
      "course",
      "module",
      "lesson",
      "curriculum",
      "kurikulum",
      "CourseChangeRequest",
      "change-requests",
      "admin/courses",
      "mentor/usulan",
      "approve",
      "reject",
    ],
  },
  {
    id: "enrollment",
    number: "6",
    label: "Enrollment, checkout & hub membership",
    keywords: [
      "enroll",
      "checkout",
      "transaction",
      "PLATFORM_COMMISSION_RATE",
      "ensureHubMembershipForCourseEnrollment",
      "pricing.ts",
      "komisi",
    ],
  },
  {
    id: "belajar",
    number: "7",
    label: "Learning: video, notes, komentar, review",
    keywords: [
      "LearningWorkspace",
      "video",
      "playback-token",
      "watermark",
      "anti-screenshot",
      "notes",
      "catatan",
      "Q&A",
      "questions",
      "progress",
      "reviews",
      "isPreviewGratis",
      "isFreeModuleLesson",
    ],
  },
  {
    id: "pendapatan",
    number: "8",
    label: "Admin pendapatan / revenue",
    keywords: [
      "revenue",
      "buildRevenueReport",
      "platformFee",
      "mentorPayout",
      "COMPLETED",
      "ESTIMATED",
      "/admin/pendapatan",
    ],
  },
  {
    id: "routes",
    number: "9",
    label: "Key routes & API map",
    keywords: ["sitemap", "halaman", "ringkasan API", "overview"],
  },
  {
    id: "api-reference",
    number: "10",
    label: "API reference lengkap",
    keywords: [
      "endpoint",
      "auth",
      "me",
      "profile",
      "avatar",
      "watchlist",
      "playlist",
      "transactions",
      "courses",
      "lessons",
      "chat",
      "trading",
      "polls",
      "signals",
      "sessions",
      "availability-slots",
      "booking",
      "1-on-1",
      "uploads",
      "thumbnail",
      "video",
      "admin",
      "mentor",
      "nextauth",
      "oauth",
      "google",
      "playback-token",
      "route.ts",
      "REST",
    ],
  },
  {
    id: "konvensi-error",
    number: "11",
    label: "Error handling & konvensi API",
    keywords: [
      "jsonOk",
      "jsonError",
      "handleApiError",
      "ZodError",
      "422",
      "401",
      "403",
      "404",
      "409",
      "429",
      "500",
      "rate limit",
      "checkRateLimit",
      "clientIp",
      "PrismaClientKnownRequestError",
      "status code",
      "validasi",
    ],
  },
  {
    id: "env-deploy",
    number: "12",
    label: "Environment variables & deployment",
    keywords: [
      ".env",
      ".env.example",
      "DATABASE_URL",
      "DIRECT_URL",
      "NEXTAUTH_SECRET",
      "AUTH_SECRET",
      "NEXTAUTH_URL",
      "GOOGLE_CLIENT_ID",
      "GOOGLE_CLIENT_SECRET",
      "vercel",
      "neon",
      "postgresql",
      "prisma migrate deploy",
      "build",
      "deploy",
    ],
  },
  {
    id: "pembayaran",
    number: "13",
    label: "Pembayaran & checkout (mock)",
    keywords: [
      "midtrans",
      "gopay",
      "ovo",
      "dana",
      "qris",
      "virtual account",
      "kartu kredit",
      "payment method",
      "webhook",
      "gateway",
      "checkout-form",
      "settings-payment",
    ],
  },
  {
    id: "setup",
    number: "14",
    label: "Setup lokal",
    keywords: [
      "npm install",
      "npm run dev",
      "db:generate",
      "db:migrate",
      "db:seed",
      "db:studio",
      "EPERM",
      "windows",
      "prisma generate",
    ],
  },
  {
    id: "privasi",
    number: "15",
    label: "Aturan privasi (wajib)",
    keywords: [
      "privacy",
      "private branch",
      "cabang privat",
      "mentor_internal",
      "isStaffCollaboration",
      "developer blocked",
      "fail-closed",
    ],
  },
  {
    id: "demo",
    number: "16",
    label: "Akun test",
    keywords: [
      "seed.ts",
      "password123",
      "demo@bursanalar.com",
      "learner@test.dev",
      "mentor@test.dev",
      "admin@test.dev",
      "developer@test.dev",
      "roleForEmail",
    ],
  },
  {
    id: "qc",
    label: "Alur QC developer",
    keywords: ["quality control", "qc hub", "checklist", "banner qc"],
  },
];
